[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
[profile.intense.fuzz]
runs = 10000
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
